version: 0.2

phases:

 pre_build:

   commands:
     - cd /server_side/topshelf/
 build:

   commands:
     - mvn test

     - echo Maven build started on `date`

     - mvn clean package

artifacts:

 files:

   - topshelf.war

   - .ebextensions/**/*

eb_codebuild_settings:

 CodeBuildServiceRole: codebuild-TopShelfAngularBuild-service-role

 ComputeType: BUILD_GENERAL1_SMALL

 Image: aws/codebuild/java:openjdk-8

 Timeout: 60

 base-directory: 'target/topshelf'
