version: 0.2

phases:

 pre_build:

   commands:

     - echo Running JUnit tests on `date`

 build:

   commands:

     - echo Maven build started on `date`

artifacts:

 files:

   - topshelf.war

eb_codebuild_settings:

 CodeBuildServiceRole: codebuild-TopShelfAngularBuild-service-role

 ComputeType: BUILD_GENERAL1_SMALL

 Image: aws/codebuild/java:openjdk-8

 Timeout: 60

 base-directory: 'target/topshelf'
