version: 0.2

phases:
  install:
    commands:
      - cd /TopShelfAngular
      - echo Installing source NPM dependencies…
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - cd /TopShelfAngular
      - echo Build started on `date`
      - ng build --prod
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Deploying production files to S3 web hosting bucket
      - aws s3 sync --delete dist s3://topshelfangularproject
      - echo Files deployed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes